### ISSUE TITLE
Previous version

### ISSUE THREAD

**Issue by PedroAQCoutinho** [AlexandreCandidoXavier/BR-DWGD#1]
Hello Alexandre, it's a pleasure.
I have been a user of your weather data for quite some time. I am in the process of publishing a study in which I used an earlier version of your data that I am unable to find.

This is a version in which the data had temporal resolution from January 1980 to December 2017, with the exception of the temperature data which went up to 2016.

Do you know where I can find this data again ? Has this been published ?

**Comment by AlexandreCandidoXavier** [comment]
Oi Pedro.

Obrigado pelo interesse nos dados. Você tentou aqui?:

https://utexas.app.box.com/v/Xavier-etal-IJOC-DATA/folder/4247252285

Acho que estão todos aí. Para ver os demais arquivos, é só ir ao final da página, que tem uma seta onde você pode ir para os próximos aquivos.

Me avise se isto funciona para você.

Abraço e bom fim de semana.

Alexandre

**Comment by PedroAQCoutinho** [comment]
Olá Alexandre muito obrigado !
Funcionou sim, encontrei os dados. São os arquivos referentes ao "BrazilMetData_1980_2017_v2_WithErrors". Estes não foram publicados, certo ? Há alguma forma de referencia-los?

Abraços

**Comment by AlexandreCandidoXavier** [comment]
Não, este nome é de uma pasta com arquivos errados. Você não deve utilizá-los.

Os arquivos estão logo abaixo. Por exemplo:

![Captura de tela 2022-05-06 17 24 56](https://user-images.githubusercontent.com/29493568/167211861-b6c4803e-ade5-4a6f-b632-a2e96bb8bbfe.png)

Entendeu?
